apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: cp
servers: 1
options:
  k3s:
    extraArgs:
      - arg: --kubelet-arg=feature-gates=KubeletInUserNamespace=true
        nodeFilters:
          - server:*
          - agent:*
