global:
  domain: argocd.127.0.0.1.nip.io
configs:
  secret:
    argocdServerAdminPassword: "$2a$10$0irC.yM40egmif.p6VvuKeGKnBqx3Cv4PBWoNpVthnuMdCfkBrGV."
    argocdServerAdminPasswordMtime: "2021-11-08T15:04:05Z"
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 60s
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
  extraArgs:
    - --insecure
